vshell_sources += [
    'widgets/workspaces.vala',
    'widgets/bar.vala',
    'widgets/active_client.vala',
    'widgets/circular_progress.vala',
    'widgets/music.vala',
    'widgets/audio_icon.vala',
    'widgets/bluetooth_icon.vala',
    'widgets/network_icon.vala',
    'widgets/apprunner.vala',
    'widgets/quicksettings.vala',
    'widgets/quick_slider.vala',
    'widgets/quick_button.vala',
    'widgets/quick_internet.vala',
    'widgets/quick_bluetooth.vala',
    'widgets/quick_power_mode.vala',
    'widgets/quick_tray.vala',
]
